package de.bascurt.almancaokuyucu

internal fun uiText(language: String, key: String): String {
    val values = uiStrings[key] ?: return key
    return values[language] ?: values["tr"] ?: key
}

private val uiStrings: Map<String, Map<String, String>> = mapOf(
    "Almanca Okuyucu" to langs("Almanca Okuyucu", "German Reader", "Lector de alemán", "Lecteur d'allemand", "Lettore di tedesco"),
    "Ana Sayfa" to langs("Ana Sayfa", "Home", "Inicio", "Accueil", "Home"),
    "Hikâyeler" to langs("Hikâyeler", "Stories", "Historias", "Histoires", "Storie"),
    "Kelimelerim" to langs("Kelimelerim", "My Words", "Mis palabras", "Mes mots", "Le mie parole"),
    "Çalış" to langs("Çalış", "Study", "Estudiar", "Étudier", "Studia"),
    "Çalışmalarım" to langs("Çalışmalarım", "Study", "Estudio", "Étude", "Studio"),
    "Profilim" to langs("Profilim", "Profile", "Perfil", "Profil", "Profilo"),
    "Tamamlanan Hikâyeler" to langs("Tamamlanan Hikâyeler", "Completed Stories", "Historias completadas", "Histoires terminées", "Storie completate"),
    "İstatistikler" to langs("İstatistikler", "Statistics", "Estadísticas", "Statistiques", "Statistiche"),
    "Ayarlar" to langs("Ayarlar", "Settings", "Ajustes", "Paramètres", "Impostazioni"),
    "Hakkında" to langs("Hakkında", "About", "Acerca de", "À propos", "Informazioni"),
    "Uygulama hakkında" to langs("Uygulama hakkında", "About the app", "Acerca de la aplicación", "À propos de l'application", "Informazioni sull'app"),
    "Dil" to langs("Dil", "Language", "Idioma", "Langue", "Lingua"),
    "Uygulama dili" to langs("Uygulama dili", "App language", "Idioma de la aplicación", "Langue de l'application", "Lingua dell'app"),
    "Menüler ve uygulama arayüzü için kullanılacak dil." to langs("Menüler ve uygulama arayüzü için kullanılacak dil.", "Language used for menus and the app interface.", "Idioma utilizado en los menús y la interfaz.", "Langue utilisée pour les menus et l'interface.", "Lingua usata per i menu e l'interfaccia."),
    "Hikâye çeviri dili" to langs("Hikâye çeviri dili", "Story translation language", "Idioma de traducción de las historias", "Langue de traduction des histoires", "Lingua di traduzione delle storie"),
    "Hikâyedeki Çeviri butonuna bastığında gösterilecek dil." to langs("Hikâyedeki Çeviri butonuna bastığında gösterilecek dil.", "Language shown when you tap Translate in a story.", "Idioma que se muestra al pulsar Traducir en una historia.", "Langue affichée lorsque vous appuyez sur Traduire dans une histoire.", "Lingua mostrata quando tocchi Traduci in una storia."),
    "Görünüm" to langs("Görünüm", "Appearance", "Apariencia", "Apparence", "Aspetto"),
    "Tema" to langs("Tema", "Theme", "Tema", "Thème", "Tema"),
    "Sistem" to langs("Sistem", "System", "Sistema", "Système", "Sistema"),
    "Açık" to langs("Açık", "Light", "Claro", "Clair", "Chiaro"),
    "Karanlık" to langs("Karanlık", "Dark", "Oscuro", "Sombre", "Scuro"),
    "Arayüz yazı boyutu" to langs("Arayüz yazı boyutu", "Interface text size", "Tamaño del texto de la interfaz", "Taille du texte de l'interface", "Dimensione testo interfaccia"),
    "Hikâye yazı boyutu" to langs("Hikâye yazı boyutu", "Story text size", "Tamaño del texto de la historia", "Taille du texte de l'histoire", "Dimensione testo storia"),
    "Okuma" to langs("Okuma", "Reading", "Lectura", "Lecture", "Lettura"),
    "Seçilen kelimeyi vurgula" to langs("Seçilen kelimeyi vurgula", "Highlight selected word", "Resaltar la palabra seleccionada", "Surligner le mot sélectionné", "Evidenzia la parola selezionata"),
    "Ayrıntılı açıklamaları göster" to langs("Ayrıntılı açıklamaları göster", "Show detailed explanations", "Mostrar explicaciones detalladas", "Afficher les explications détaillées", "Mostra spiegazioni dettagliate"),
    "Sınav" to langs("Sınav", "Quiz", "Prueba", "Quiz", "Quiz"),
    "Hikâye sınavında soru sayısı" to langs("Hikâye sınavında soru sayısı", "Questions in story quiz", "Preguntas en la prueba de la historia", "Questions dans le quiz de l'histoire", "Domande nel quiz della storia"),
    "Değişiklikleri kaydet" to langs("Değişiklikleri kaydet", "Save changes", "Guardar cambios", "Enregistrer les modifications", "Salva modifiche"),
    "Değişiklikler kaydedildi" to langs("Değişiklikler kaydedildi", "Changes saved", "Cambios guardados", "Modifications enregistrées", "Modifiche salvate"),
    "Kaydedilmemiş değişiklikler" to langs("Kaydedilmemiş değişiklikler", "Unsaved changes", "Cambios sin guardar", "Modifications non enregistrées", "Modifiche non salvate"),
    "Değişiklikler kaydedilsin mi?" to langs("Değişiklikler kaydedilsin mi?", "Save your changes?", "¿Guardar los cambios?", "Enregistrer les modifications ?", "Salvare le modifiche?"),
    "Kaydet ve çık" to langs("Kaydet ve çık", "Save and leave", "Guardar y salir", "Enregistrer et quitter", "Salva ed esci"),
    "Kaydetmeden çık" to langs("Kaydetmeden çık", "Leave without saving", "Salir sin guardar", "Quitter sans enregistrer", "Esci senza salvare"),
    "Vazgeç" to langs("Vazgeç", "Cancel", "Cancelar", "Annuler", "Annulla"),
    "Uygulamayı tamamen sıfırla" to langs("Uygulamayı tamamen sıfırla", "Reset app completely", "Restablecer la aplicación", "Réinitialiser l'application", "Reimposta completamente l'app"),
    "Uygulama sıfırlansın mı?" to langs("Uygulama sıfırlansın mı?", "Reset the app?", "¿Restablecer la aplicación?", "Réinitialiser l'application ?", "Reimpostare l'app?"),
    "Tamamen sıfırla" to langs("Tamamen sıfırla", "Reset completely", "Restablecer por completo", "Réinitialiser complètement", "Reimposta completamente"),
    "Çeviri" to langs("Çeviri", "Translate", "Traducir", "Traduire", "Traduci"),
    "Çeviriyi Gizle" to langs("Çeviriyi Gizle", "Hide translation", "Ocultar traducción", "Masquer la traduction", "Nascondi traduzione"),
    "Hikâye" to langs("Hikâye", "Story", "Historia", "Histoire", "Storia"),
    "Kelimeler" to langs("Kelimeler", "Words", "Palabras", "Mots", "Parole"),
    "Gramer" to langs("Gramer", "Grammar", "Gramática", "Grammaire", "Grammatica"),
    "Bir kelimeye dokun" to langs("Bir kelimeye dokun", "Tap a word", "Toca una palabra", "Touchez un mot", "Tocca una parola"),
    "Anlamı, kelime türü ve kullanım bilgisi burada görünecek." to langs("Anlamı, kelime türü ve kullanım bilgisi burada görünecek.", "Meaning, word type and usage will appear here.", "Aquí aparecerán el significado, el tipo de palabra y el uso.", "Le sens, le type de mot et l'usage apparaîtront ici.", "Qui appariranno significato, tipo di parola e uso."),
    "Kelime türü" to langs("Kelime türü", "Word type", "Tipo de palabra", "Type de mot", "Tipo di parola"),
    "Artikel" to langs("Artikel", "Article", "Artículo", "Article", "Articolo"),
    "Çoğul" to langs("Çoğul", "Plural", "Plural", "Pluriel", "Plurale"),
    "Anlam" to langs("Anlam", "Meaning", "Significado", "Sens", "Significato"),
    "Bu cümlede" to langs("Bu cümlede", "In this sentence", "En esta frase", "Dans cette phrase", "In questa frase"),
    "Mastar" to langs("Mastar", "Infinitive", "Infinitivo", "Infinitif", "Infinito"),
    "3. tekil şahıs" to langs("3. tekil şahıs", "3rd person singular", "3.ª persona singular", "3e personne du singulier", "3ª persona singolare"),
    "Yalın hâl" to langs("Yalın hâl", "Positive form", "Forma positiva", "Forme positive", "Forma positiva"),
    "Hikâye tamamlandı" to langs("Hikâye tamamlandı", "Story completed", "Historia completada", "Histoire terminée", "Storia completata"),
    "Tamamlandı işaretini kaldır" to langs("Tamamlandı işaretini kaldır", "Remove completed mark", "Quitar marca de completada", "Retirer la marque terminée", "Rimuovi il completamento"),
    "Hikâyeyi tamamlandı olarak işaretle" to langs("Hikâyeyi tamamlandı olarak işaretle", "Mark story as completed", "Marcar historia como completada", "Marquer l'histoire comme terminée", "Segna la storia come completata"),
    "Başla" to langs("Başla", "Start", "Empezar", "Commencer", "Inizia"),
    "Sonraki" to langs("Sonraki", "Next", "Siguiente", "Suivant", "Avanti"),
    "Doğru" to langs("Doğru", "Correct", "Correcto", "Correct", "Corretto"),
    "Doğru cevap" to langs("Doğru cevap", "Correct answer", "Respuesta correcta", "Bonne réponse", "Risposta corretta"),
    "Kelime Çalışması" to langs("Kelime Çalışması", "Word Study", "Estudio de palabras", "Étude des mots", "Studio delle parole"),
    "Boşluk Doldurma" to langs("Boşluk Doldurma", "Fill in the Blank", "Completar huecos", "Texte à trous", "Completa gli spazi"),
    "Türkçe" to langs("Türkçe", "Turkish", "Turco", "Turc", "Turco"),
    "İngilizce" to langs("İngilizce", "English", "Inglés", "Anglais", "Inglese"),
    "İspanyolca" to langs("İspanyolca", "Spanish", "Español", "Espagnol", "Spagnolo"),
    "Fransızca" to langs("Fransızca", "French", "Francés", "Français", "Francese"),
    "İtalyanca" to langs("İtalyanca", "Italian", "Italiano", "Italien", "Italiano")
)

private fun langs(tr: String, en: String, es: String, fr: String, it: String): Map<String, String> =
    mapOf("tr" to tr, "en" to en, "es" to es, "fr" to fr, "it" to it)
